### ISSUE TITLE
Unwrap rewrapped Text

### ISSUE THREAD

**Issue by tabedzki** [stkb/Rewrap#107]
I know that this might seem counter-intuitive but is it possible to build a command (and maybe map it to `Alt + Shift + q`) to undo a rewrap (which essentially is like a 'rewrap' at a very large number)?  I like writing in VS Code but ultimately I have to submit documents in Word files for people who are uncomfortable with plain text files/for some grant applications. I would greatly appreciate this feature.

**Comment by syifan** [comment]
An alternative solution is to use vscode-vim plugin and type `vipJ`. It will unwrap the paragraph where your cursor is at.

**Comment by gavinr** [comment]
I would greatly appreciate this feature too!

**Comment by stkb** [comment]
@gavinr Thanks for the offer! I'll take a PR if you've already started work on it, but now this has my attention :) I think I can easily add a command that can do this.

**Comment by gavinr** [comment]
I have not started it - would appreciate it! Thanks!

**Comment by stkb** [comment]
While developing this feature I found that not only would adding it be very easy (simply by doing a normal wrap with a very large column number) it was actually possible to do this with extension already!

There already exists the command `Rewrap Comment / Text at column...` which allows the user to do a (one-time) wrap at the given column number. So if you just put a very large number in here, you'll get what you want.

Now, I appreciate this isn't great UX for unwrapping (typing in an arbitrary large number etc.). At the same time I'm rather obsessive about this extension's footprint on the editor, and am reluctant to add another (less commonly used) command.

So I've modified that existing command a little to make it more suitable for unwrapping. I've renamed it "Rewrap/**Unwrap** Text at Column" (search for 'unwrap'). I've also made it so that the field is blank to start with, and if it's blank it will remove wrapping instead. The help-text next to it explains that too.

![image](https://user-images.githubusercontent.com/6125444/82576284-f5823f00-9b89-11ea-9d86-9fee628cc865.png)

I hope this will be sufficient! I plan to add this change in the next release in the next few days, but if you want to, you can [download the beta version](https://github.com/stkb/Rewrap/releases/tag/beta) now to try it out.

**Comment by gavinr** [comment]
Works for me! Thank you very much!

**Comment by stkb** [comment]
This is now in v1.11.0 so I'm closing

**Comment by yasirroni** [comment]
The most convenient approach that I found is to use `setting.json`:

```
{
    "editor.rulers": [80,1000]
}
```

This way, you can use `alt + Q` two times to choose between wrap and unwrap. How about set this as feature? @stkb 

Or maybe put this on the docs?

**Comment by yasirroni** [comment]
This is what I found, `"editor.rulers": [80,0]` will be my choice:

```
{
    // "editor.rulers": [1000,80,0] // wrap 3, unwrap 2 **
    "editor.rulers": [80,0] // wrap 2, unwrap 2 *
    // "editor.rulers": [0,80] // wrap 1, unwrap not possible
    // "editor.rulers": [1000,80] // wrap 2, unwrap 2 *
    // "editor.rulers": [80,1000] // wrap 2, unwrap 2 *
    // "editor.rulers": [0,80,1000] // wrap 1, unwrap not possible

    // * on short text: wrap 1, unwrap 1
    // ** on short text: wrap 2, unwrap 1
}
```

**Comment by yasirroni** [comment]
> @gavinr Thanks for the offer! I'll take a PR if you've already started work on it, but now this has my attention :) I think I can easily add a command that can do this.

Someone already add PR [rgson:feature/unwrap-cmd](https://github.com/stkb/Rewrap/pull/272#issue-891056777)?
