### ISSUE TITLE
error message: command 'rewrap.rewrapComment' not found

### ISSUE THREAD

**Issue by simmdan** [stkb/Rewrap#132]
Running on windows 10, VS Code 1.31.1, rewrap version 1.9.1.  When I press alt-q or try to run any of the three rewrap commands in the command palette, I get a message saying the command is not found as shown in the title of this issue.

Unfortunately, when I tried installing vscode and the rewrap extension on a different machine also running windows 10, the problem did not repro.  On my main machine, however, I can't seem to get it to go away.  I tried uninstalling and reinstalling vscode as well as all of my extensions.  On a fresh install of vscode with just the rewrap extension the problem continues to manifest.

My settings.json file contains only:

{
    "window.zoomLevel": 0,    
    "editor.minimap.enabled": false,
    "workbench.activityBar.visible": true
}

Any ideas about other things I can check on or other data I can provide to help track this down?

Thanks in advance for your help and for this great extension (when I have had it working in the past I find it VERY useful).

**Comment by simmdan** [comment]
I eventually did a compare of the extension directory on vscode on my machine where it didn't work and the one where it did and discovered that there was no node_modules directory present on the machine where it didn't work.  I copied the node_modules directory from the one where it was working, and it fixed.  I then uninstalled the extension, made sure the directory for the extension was removed, and reinstalled it.  This time it properly installed the node_modules directory.

So, I have no idea how I got into that state, but apparently the problem no longer repros.

Interesting that there was no error that I could see when it was unable to load because it couldn't find the modules it depended on, but at any rate, I now know something else to look for if this kind of thing happens again in the future.

**Comment by simmdan** [comment]
Sadly, this exact same thing happened to me again.  Without doing anything specific related to rewrap--just using VS Code for regular tasks and letting it and rewrap auto-update periodically, today I discovered that I was getting the same symptom as above (error about rewrapComment not being found when I pressed the hotkey).  I discovered that the extension once again didn't have node_modules.  To fix it, I had to uninstall the extension, then manually delete the extension directory (it wasn't deleted when I uninstalled) and reinstall it.  Then node_modules appeared and things started working.

**Comment by jemmyw** [comment]
I ran into the exact same issue. Thanks @simmdan I followed your steps to rectify.

**Comment by simmdan** [comment]
And for what it's worth, it just happened to me again, and the same steps fixed it.  At least I know to come back to this issue to remind me what to do.  Wish I had a clue what caused the problem.

**Comment by simmdan** [comment]
Looks like it happened to another extension as well.  So this doesn't appear to be specific to Rewrap.  Probably it's feedback that should go direct to VSCode--at least about the fact that uninstalling and reinstalling doesn't fix it unless you manually delete the extension's directory.

**Comment by stkb** [comment]
@simmdan Thanks for the update. The node_modules folder & all code required to run the extension is included in the .vsix file; nothing is downloaded on install or anything like that, so I really don't know what's happening here.

**Comment by asbjornu** [comment]
This happened to me just now.  My environment:

```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

**Comment by asbjornu** [comment]
I think the bug experienced here may be microsoft/vscode#114256.

**Comment by kylecordes** [comment]
This issue is now affecting me also. I don't know what triggered it - I've been using rewrap for years.

BTW the vscode issue linked in the previous comment was auto-closed by a bot without any progress on the problem... which seems to be the fate of issues in many projects nowadays.

When the error occurs it points to the dev tools console, which contains the long error message below. Unfortunately its appears the code is all minified, so it's tough to see anything in this message.


  ERR [Extension Host] ====== Rewrap: Error ======
console.ts:137 [Extension Host] ====== Rewrap: Error ====== (at $0d70716f788862e9$export$7cc2a9afec49ab22 (/Users/kcordes/.vscode-insiders/extensions/stkb.rewrap-1.15.2/dist/Extension.js:11245:13))
E @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
console.ts:137 [Extension Host] TypeError: Cannot read property '0' of null	at $840f1b1ae3c3949d$var$maybeAddCustomLanguage (/Users/kcordes/.vscode-insiders/extensions/stkb.rewrap-1.15.2/dist/Extension.js:10420:33)	at /Users/kcordes/.vscode-insiders/extensions/stkb.rewrap-1.15.2/dist/Extension.js:10443:102	at $cbf049927489a6e9$export$c90763f2293d7e67 (/Users/kcordes/.vscode-insiders/extensions/stkb.rewrap-1.15.2/dist/Extension.js:3353:75)	at $840f1b1ae3c3949d$export$2e6c959c16ff56b8 (/Users/kcordes/.vscode-insiders/extensions/stkb.rewrap-1.15.2/dist/Extension.js:10443:7)	at $900a7436dc584467$export$6cb9d9886761bf2b (/Users/kcordes/.vscode-insiders/extensions/stkb.rewrap-1.15.2/dist/Extension.js:11013:20)	at $fad922d34226e04f$var$doWrap (/Users/kcordes/.vscode-insiders/extensions/stkb.rewrap-1.15.2/dist/Extension.js:11554:22)	at rewrapCommentCommand (/Users/kcordes/.vscode-insiders/extensions/stkb.rewrap-1.15.2/dist/Extension.js:11515:9)	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:21485	at Object.edit (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:51685)	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:21472	at a._executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:111318)	at a.$executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:111860)	at t._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13802)	at t._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13486)	at t._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:12148)	at t._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:10826)	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:8922	at c.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)	at s.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15990)	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:30519	at c.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)	at s.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15990)	at h._receiveMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21260)	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:18138	at c.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)	at w.acceptChunk (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:13351)	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:12699	at Socket.m (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:13547)	at Socket.emit (events.js:315:20)	at addChunk (internal/streams/readable.js:309:12)	at readableAddChunk (internal/streams/readable.js:284:9)	at Socket.Readable.push (internal/streams/readable.js:223:10)	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) (at $0d70716f788862e9$export$7cc2a9afec49ab22 (/Users/kcordes/.vscode-insiders/extensions/stkb.rewrap-1.15.2/dist/Extension.js:11246:13))
log.ts:313   ERR [Extension Host] ^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^
at https://github.com/stkb/vscode-rewrap/issues
console.ts:137 [Extension Host] ^^^^^^ Rewrap: Please report this (with a copy of the above lines) ^^^^^^at https://github.com/stkb/vscode-rewrap/issues (at $0d70716f788862e9$export$7cc2a9afec49ab22 (/Users/kcordes/.vscode-insiders/extensions/stkb.rewrap-1.15.2/dist/Extension.js:11247:13))

**Comment by stkb** [comment]
@kylecordes Thanks, that stack trace actually helped me a lot in your case (it's probably different from the original issue).

I think I have it fixed, but could you tell me what file type it is you're having the bug on, and if you have an extension installed for that language type?

I've also made an updated version; could you try installing it to see if it fixes it? (Rename the file from .zip to .vsix, then in the VSCode extensions sidebar: 3-dot menu -> "Install from VSIX..." and pick the file.) You'll need to restart VSCode as prompted and you should then have Rewrap v1.15.3-beta.1

[rewrap-1.15.3-beta.1.zip](https://github.com/stkb/Rewrap/files/7525692/rewrap-1.15.3-beta.1.zip)

**Comment by kylecordes** [comment]
I experienced this error a couple days ago editing a `BUILD.bazel` file, aided by the `bazelbuild.vscode-bazel` extension. I just verified it still fails in the same way today, with the published version.

Then I installed your beta.1 above, and rewrap now works correctly in the exact context it failed before.

Thank you!

**Comment by stkb** [comment]
@kylecordes fantastic, thanks 👍  I've published the fix now.

Going to close this now as the original problem is still unclear. People can create another issue if they experience errors.
