### ISSUE TITLE
Option to enable forced double space

### ISSUE THREAD

**Issue by leeopop** [stkb/Rewrap#138]
Inserting double space between sentences only works when formatting non-rewrapped paragraph.

We have frequent use case of changing the spacing scheme (single-to-double or vice versa).

I hope there is a option to force full reformatting of comments including the spacing scheme.

**Comment by stkb** [comment]
While I feel this is rather out of scope for this extension I'm not completely against it, since the option to do this can be added to the current `doubleSentenceSpacing` option.

However attempting to reformat the sentence spacing for a block of text could run into issues.

So I'm going to need more people wanting this feature before trying to implement it.

**Comment by stkb** [comment]
Closing in favor of #301
