### ISSUE TITLE
Suggestion: setting to hide from VS Code status bar

### ISSUE THREAD

**Issue by OliverJAsh** [stkb/Rewrap#144]
Thanks for the awesome extension.

Would this be possible? I don't want it in my status bar. 😄 

![image](https://user-images.githubusercontent.com/921609/58382936-6d924500-7fc8-11e9-941a-c457e2dc088e.png)

**Comment by stkb** [comment]
Hi, that message only shows for 7 seconds, when you toggle the setting (with `alt+shift+q`), or when you start up vscode. Are you saying:
1. You don't want it to appear when toggling the setting?
2. You don't want it to appear when vscode starts up?

Or both of the above? (2) is easiest to accomplish.

**Comment by OliverJAsh** [comment]
I think 2. The reason why is because VS Code has a lot of other stuff to show in the status bar—it's quite crowded!

**Comment by kbd** [comment]
Since after this ticket was opened, VSCode now makes it possible to [hide individual status bar items](https://code.visualstudio.com/updates/v1_36#_hide-individual-status-bar-items). Therefore, I suggest the opposite: Always show Rewrap's auto-wrap setting in the status bar, and users can hide it if they don't want to see it.

I'd really prefer to either: 1. always see the status, or 2. always see the status for that session after you toggle it. FWIW, the current behavior of only showing immediately after you toggle, and only temporarily for N seconds, was very surprising to me. Usually, status bar items are permanent.

**Comment by stkb** [comment]
This will now be fixed in the next release. See https://github.com/stkb/Rewrap/issues/149#issuecomment-677708171.

**Comment by stkb** [comment]
Is fixed in v1.14.0
