### ISSUE TITLE
Support for postgres (.pgsql)

### ISSUE THREAD

**Issue by limitless-dev** [stkb/Rewrap#219]
Any chance you could add support for .pgsql?
It has similar comment structure to .sql

**Comment by stkb** [comment]
Hi, if you have a PostgreSQL extension installed like https://marketplace.visualstudio.com/items?itemName=ckolkman.vscode-postgres, it should now work in v1.13.0 (there was a bug preventing this in 1.12.0).

Also, since .pgsql comments are basically the same as .sql, I'll add native support to the next version.
