### ISSUE TITLE
Per-Language: autoWrap enable/disable

### ISSUE THREAD

**Issue by christiantjl** [stkb/Rewrap#220]
I know it's not officially supported yet, and this is definitely my favorite VS Code plugin so far, but unfortunately I can't enable `autoWrap` for *just* Javascript (or disable it for *just* Markdown, which is what I really want). Any shot at support for this?

Example in `settings.json`:
```
{
    ...
    // markdown only
    "[markdown]": {
        "rewrap.autoWrap.enabled": false,
    },

    // global setting
    "rewrap.autoWrap.enabled": true,
    ...
}
```

**Comment by orange-droplet** [comment]
A temporary workaround for this problem is to change `"rewrap.wrappingColumn"` to a very large number for those specific languages, and leave `autoWrap` to be enabled at all time.

For example, for `markdown`, in `settings.json`:
```JSON
  // markdown only
  "[markdown]":{
    "rewrap.wrappingColumn": 9999,
  },
```
As such Rewrap will not be automatically activated until the line reaches 9999 columns, which is basically never. Manually activating Rewrap via `Ctrl+Shift+P` (Command Palatte) should still work.

Of course this solution is not elegant whatsoever, and it would definitely be better if there is an officially supported way of doing this.

**Comment by christiantjl** [comment]
That’s very smart actually, thank you very much for the response. At this
point though, I’ve just gotten used to Markdown rewrapping. 😂 It knows not
to mess up table cells even, so it’s pretty workable.

It’s also honestly nice to have 80 column wide files universally at the end
of the day.

Best VS Code plugin, should really be pulled into the IDE itself as default
behavior.

**Comment by stkb** [comment]
Closing as dup of #149. This will be in the next release

**Comment by christiantjl** [comment]
Thank you @stkb. This plugin has made my life infinitely easier.
