### ISSUE TITLE
Unwrap does nothing when "Wrapping Column" config set.

### ISSUE THREAD

**Issue by jpap** [stkb/Rewrap#264]
Thanks for writing this awesome extension!

I have set a custom wrapping column in the extension config.  After that, I can wrap a line using the keyboard shortcut, but when repeating the shortcut, the line does not unwrap (nothing happens).  If I reset the custom wrapping column setting back to the default, unwrapping works.

Edit: it appears that subsequent invocations of rewrap will just rewrap the comment block to the custom wrapping column.  For example, I write a comment block, rewrap it, edit the block, rewrap it.  When there are no edits, Rewrap does nothing because the result of the wrap is the same.  It would be nice to toggle between wrapped and unwrapped if the result would otherwise be the same.

**Comment by stkb** [comment]
Hi!

Firstly after doing any wrap you can always use ctrl+z to undo it.

Now, while the extension doesn't do exactly what you're describing, you can use [an existing feature](http://stkb.github.io/Rewrap/#/settings-vscode?id=wrapping-to-rulers) to achieve it.

First, instead of using the "Rewrap: Wrapping Column" setting (set this back to 0), you need to use "Editor: Rulers" instead. Set here two rulers: one for the normal wrapping column you want, and the 2nd one at zero. Example if you want the wrapping column at 80:

User settings json:
``` json
{
  "editor.rulers": [80, 0]
}
```

Now it will do exactly as you described. If there is no change, it will toggle between wrapped and unwrapped.

---

However that ruler at column zero gives you a quite ugly line at the left of the editor. So you can solve it in one of 3 ways:

If you don't want any rulers visible in the editor, change their color to match the background of your editor. Eg in user settings:
``` json
{
  "workbench.colorCustomizations": {
    "editorRuler.foreground": "#fff"
  }
}
```

If you want the "normal" ruler visible but not the other, you can set their colors individually:
``` json
{
  "editor.rulers": [
    { "column": 80, "color": "#aaa" },
    { "column": 0, "color": "#fff" }
  ]
}
```


Or lastly, instead of 0, you can use a really big number for the second ruler instead, so it will (practically) never be visible:
``` json
{
  "editor.rulers": [80, 9999999]
}
```

Does this achieve what you want?

**Comment by jpap** [comment]
Wrapping to rulers, and cycling through them, is awesome! I can work with that. Thank you for the thoughtful and detailed response.
