### ISSUE TITLE
VS2022 Compat

### ISSUE THREAD

**Issue by mikernet** [stkb/Rewrap#281]
Would love a VS2022 compatibility update :)

**Comment by user72356** [comment]
I'm with you on that brother.

**Comment by CodeBlanch** [comment]
@stkb Love this extension it has become critical to my workflow I would be eternally grateful if you pushed out a 64bit version for VS2022 😄

**Comment by cmeeren** [comment]
Ditto, would love to see this for VS2022.

**Comment by stkb** [comment]
Hi guys, I've been working on this for a few days and it's been quite a ride, because of the breaking changes VS2022, and I though I would have to split the extension into 2 versions. Fortunately I think I've found a workaround.

The new version 1.15.0 is in the marketplace and supports 2017, 2019 & 2022. I dropped support for 2015 but hopefully nobody will miss that :). It's working for me in 2019 & 2022.

Unfortunately as always if you have custom settings for Rewrap, they don't migrate over between VS versions. Maybe one day I'll write an import/export.

Hopefully it works for you.

**Comment by CodeBlanch** [comment]
Thanks @stkb! Just tried it, getting a dialog alert with `Object reference not set to an instance of an object` highlighting some text and doing alt+q to re-wrap.

**Comment by stkb** [comment]
@CodeBlanch Damn, as I say it's working fine for me.

Are you on VS 17.0.0? What type of file is it you're working on and do you have any custom Rewrap settings?

**Comment by CodeBlanch** [comment]
@stkb Sorry I should have mentioned I'm using 17.1.0 Preview 1. No custom settings. I tried on a .cs file and a .md file, both had the error. Asked a colleague to try on 17.0.0, he says it works fine for him.

**Comment by bddckr** [comment]
Thanks a lot for the extension and the update for VS 2022!!!

I am having the same issue on 17.1.0 Preview 1. I've tried running VS with `/Log` but there's neither any mention of Rewrap (besides entries saying the package loaded successfully), a null ref exception, nor is there any entry with the timestamp at which I triggered the issue. 🤔

Debugging Rewrap shows it's coming from here:
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Rewrap-VS
  StackTrace:
   at VS.Editor.GetRulers() in C:\Projects\Rewrap\vs\Editor.cs:line 236
```

Guarding that section with a simple null check makes it work for me!
```c#
if (guidesStr is null)
{
    return new int[0];
}
```

---

Btw, these two happen sometimes when I close the debugged VS instance:
```
Managed Debugging Assistant 'CallbackOnCollectedDelegate' 
  Message=Managed Debugging Assistant 'CallbackOnCollectedDelegate' : 'A callback was made on a garbage collected delegate of type 'Microsoft.VisualStudio.DesignTools.WpfTap!Microsoft.VisualStudio.DesignTools.WpfTap.NativeMethods+WinEventDelegate::Invoke'. This may cause application crashes, corruption and data loss. When passing delegates to unmanaged code, they must be kept alive by the managed application until it is guaranteed that they will never be called.'
```

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

**Comment by stkb** [comment]
@CodeBlanch @bddckr Thanks, yeah I installed 17.1 preview and can repro. Fix should be coming soon

**Comment by stkb** [comment]
OK I've pushed v15.0.0.1 to the marketplace which should fix things for VS 17.1. Though I haven't been able to test it with guidelines since [that extension's also broken in 17.1](https://github.com/pharring/EditorGuidelines/issues/87) :)

**Comment by bddckr** [comment]
It works for me now, thanks a lot!

**Comment by CodeBlanch** [comment]
Thanks @stkb working for me now!

**Comment by stkb** [comment]
@bddckr @CodeBlanch Cool, for reference it was because they've changed how VS reports its version number. Previously it was only the major version: eg with version 16.1, 16.2 etc it would still return "16.0...". Now with v17.1, it actually reports "17.1...". 

However the path to the registry entries still uses "17.0", not "17.1" which was the reason for the error. So anyway I've made that code more robust now.
