### ISSUE TITLE
Feature request: rewrap paragraph

### ISSUE THREAD

**Issue by cortesi** [stkb/Rewrap#29]
For longer comments that include some formatting, it would be useful to have a "rewrap paragraph" command that only rewraps the current paragraph within a comment, leaving the rest of the comment as-is.

**Comment by stkb** [comment]
This is maybe how it should have worked by default and that might still be something to consider changing, or having a setting that changes it.

However I don't really want to resort to adding another command just yet. If #28 (lists) can be fixed, would that solve most cases for you? Are there any other types of formatting that you regularly use that get messed up? Hopefully the majority of cases can be covered, and for the rest you can always select just the lines you want before wrapping.

**Comment by cortesi** [comment]
Oh, there's a huge range - from ASCII flowcharts, to automatic documentation generation systems, to idiosyncrasies that have to be preserved because they're codebase-wide and the code is not my own. At the moment, rewrap buggers up a sizeable fraction of longer comments for me, so I'm in the habit of visual selecting individual chunks and formatting them instead. Not having a format-this-paragraph shortcut is a mild but constant annoyance (gqap used to be wired into my fingers in vim). For what it's worth, I think "format this entire comment" is also useful to have, especially in my own code where I can make sure that comments are properly structured.

**Comment by stkb** [comment]
Ok you're convincing me this is necessary. But I still want to try it as a setting first. I'll have a version in the next few days that deals with this and #28 for you to try out.

**Comment by cortesi** [comment]
Excellent - I look forward to trying it. And thank you for your work on this - I live in my editor, and your addon makes coding a bit better all day long.

**Comment by retep998** [comment]
Instead of having a new command, maybe it could change it's behavior whether you have text selected. If you do, then it rewraps all lines covered by the selection, otherwise it has the current behavior. That way I could select precise paragraphs and bullet points and reflow exactly what I want.

**Comment by stkb** [comment]
@retep998 The current version already restricts rewrapping to just the selected lines if the selection is nonempty.

However I've finally added a setting in the upcoming version to give this option (and yeah it's been more than a few days 😃). See #40

**Comment by stkb** [comment]
Ok it's been several months but a solution is now in the published version 1.4.0. You can use the `rewrap.wholeComment` setting and set it to `false` so that it only wraps the containing paragraph in the comment.

I prefer to add settings rather than extra commands, since people can then choose any combination of settings they wish, whereas with commands I'd end up having to add extra commands for all possible combinations. I'm not completely happy with this though and am looking into ways to either be able to quickly change settings or let the user create a custom extra command with alternative settings. I'll close this issue for now though.
