### ISSUE TITLE
Feature request: wrap to each ruler

### ISSUE THREAD

**Issue by GaryBoone** [stkb/Rewrap#30]
If there are multiple rulers, vscode-rewrap wraps to the first one. It would be super useful if it would wrap to each one of them as the wrap key is pressed. 

The reason I have multiple rulers is that in working with many projects/codebases/languages, there are many line lengths in use, whether due to different language style guides or even varying project conventions.

Instead of reconfiguring for each project, it would be natural to just mash the rewrap key several times, each time wrapping to one of the ruler settings, until the right one is found.

Users with only one ruler setting wouldn't see this behavior. It would only wrap to their single setting. So it would behave as it does now for those users.

Perhaps even include 'undo' in the list, so that the n+1 keypress returns the text to the unwrapped version. Faster than reaching for undo.

**Comment by stkb** [comment]
Hi, sorry never got to replying to this sooner. I don't know how you still feel about this feature.

At first I thought it was way too complicated but then I thought maybe it was kinda neat. I can't decide if it's a good idea; it might be confusing/irritating, but I might give it a try now that some other things are out of the way.

**Comment by stkb** [comment]
![rulers1](https://user-images.githubusercontent.com/6125444/29752890-c519b072-8b66-11e7-8782-a66c8cf43832.gif)

This is now in v1.5.0. The clincher for me was that the Visual Studio version kinda needed it, since you can't have per-language ruler settings there.

The only thing it doesn't have is the undo feature. Full details at https://github.com/stkb/Rewrap/wiki/Settings-VSCode#wrapping-to-rulers
