### ISSUE TITLE
Wrapping in lua removes newlines

### ISSUE THREAD

**Issue by anantoghosh** [stkb/Rewrap#41]
If I try to wrap this lua code (Select all -> alt+Q)
```lua
local function dump()
    local a = 1
    local b = 2
    local d
    d = a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + b;
end
```
I get
```lua
local function dump()
    local a = 1 local b = 2 local d d = a + a + a + a + a + a + a + a + a + a +
    a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a + a +
    a + a + a + a + a + b
end
```
Though this is still valid lua code but not the expected output.

**Comment by stkb** [comment]
Yeah this is will happen with any type of source code file because of how Rewrap works. 

It's not designed to wrap source code (that's far too complex), and if you have any comment(s) within the selected text, it will just wrap the comments and leave the source code alone. However if you select just source code, it assumes you know what you're doing but can only treat it like plain text (this can be useful in certain types of data files).

Because there aren't any comments in that file, that's what's happening here. If you add at least one comment to that file, and then (select all -> alt+Q), the comment(s) will be wrapped but the code won't be touched.

**Comment by anantoghosh** [comment]
@stkb ah ok understood
