### ISSUE TITLE
Go pre-formatted text

### ISSUE THREAD

**Issue by larhun** [stkb/Rewrap#70]
Thanks for your great extension!

From [godoc](https://blog.golang.org/godoc-documenting-go-code):

> There are a few formatting rules that Godoc uses when converting comments to HTML: ...
> - Pre-formatted text must be indented relative to the surrounding comment text ...

Indented lines (relative to the surrounding) usually provide code fragments and should not be rewrapped.

**Comment by larhun** [comment]
The main problem is that it does not work with line comments like this:

```
// The encode algorithm looks like this:
//
//    var u uint
//    if i < 0 {
//        u = (^uint(i) << 1) | 1 // complement i, bit 0 is 1
//    } else {
//        u  = (uint(i) << 1) // do not complement i, bit 0 is 0
//    }
//    encodeUnsigned(u)
//
// The low bit is therefore analogous to a sign bit,
```
A Go comment parser would definitely be better. Losing all the other markdown features, which are not used by Godoc, is not a problem at all.

**Comment by stkb** [comment]
Ok in that example the only problem is that the indented section needs indenting 1 extra space (it's currently at 3 instead of 4).

However, while I need to consider it a little more, I think I agree with you that changing to a parser that matches exactly how godoc works is the way to go.

**Comment by larhun** [comment]
Thanks a lot. One extra space works.

**Comment by stkb** [comment]
Have made this change in v1.7.0. It now no longer uses markdown and instead (almost) reflects the godoc parsing exactly.

It should work as expected now so will close this, but there are 3 small things that aren't quite the same as in godoc. The first I still plan to fix; the other two maybe not.

In godoc the indent of "normal" paragraphs is taken from the least-indented line in the whole comment block. This allows comments that start with preformatted sections. In Rewrap the "standard" indent is taken from the first line with text, so comments can't start with preformatted sections.

Example: this is fine

    // normal text
    //   preformatted text

but here the first line isn't detected as preformatted.

    //   preformatted text
    // normal text

Second, in Rewrap, all tabs _inside_ a comment are converted to spaces (the correct number according to the editor settings and position), to keep things simple. (Tabs *before* the `//` marker are preserved.). Godoc can do some weird things when you mix tabs and spaces as internal indents.

The third is what happens when some comment markers are misaligned, eg:

    // Line 1
    // Line 2
      // Line 3

Godoc effectvely shifts the lines so that the markers re-aligned, and then processed the text from there.

    // Line 1
    // Line 2
    // Line 3

However Rewrap ignores the position of the markers  (it takes it from the first line) and looks at the position of the text instead.

    // Line 1
    // Line 2
    //   Line 3
