### ISSUE TITLE
Wrap comment lines that begin with double hash

### ISSUE THREAD

**Issue by felipe1982** [stkb/Rewrap#74]
This comment does not wrap at all:
```
## comment 1 with double hash
```
If I remove all hashes but one, it wraps as expected.

Thanks.

**Comment by stkb** [comment]
Which language is this?

**Comment by felipe1982** [comment]
Just YAML (Ansible, or CloudFormation).

**Comment by stkb** [comment]
Hi, this was because all characters after the first '#' were treated as markdown, and therefore as a heading (`# Heading`), which aren't wrappable. 

I've changed it so that the comment prefix can be up to three '###'s (that should be enough? If I make it unlimited I have to change some other code.)

If you want to test the change already you can download v1.8.0-beta1 from https://github.com/stkb/Rewrap/releases/tag/v1.8.0-beta1. (When the next version is released, it'll automatically upgrade)

Note that if you mix the number of leading ##'s in a single comment block, they'll be "normalized" to that of the first line of text. Eg:

    ## Some very long line of text      ->      ## Some very long line ¦ 
    # Some more text.      ¦                    ## of text. Some more  ¦
                                                ## text.               ¦

**Comment by stkb** [comment]
Fixed in v1.8.0
