### ISSUE TITLE
Support wrapping CJK contents

### ISSUE THREAD

**Issue by ProgramFan** [stkb/Rewrap#75]
VS Code itself wraps CJK contents correctly, but rewrap only breaks lines at English word boundary. Can this be improved? How VS Code compute the wrap goes in https://github.com/Microsoft/vscode/issues/12421.

**Comment by stkb** [comment]
Ok, I will look into this. It will take some time to get right, but I want to support it of course.

**Comment by starship863** [comment]
Thank stkb very much for this wonderful extension and for the CJK support.

This is really important for CJK users.

**Comment by stkb** [comment]
Hi guys,

@starship863 thanks for the kind words :)

I've now released a [beta version to test](https://github.com/stkb/Rewrap/releases/tag/v1.9.0-beta1) with CJK support.

![cjkwrapping](https://user-images.githubusercontent.com/6125444/38566184-5df10920-3ce3-11e8-825f-eec16aa38b1c.gif)

Please try it out and let me know what problems there are :)

**A note**: it's currently treating full-width characters as exactly 2 columns wide. However in the font I'm using (consolas), those glyphs are visually slightly less than that. So even though the paragraph is reported as 80 chars wide, visually it's not quite 80 chars (can be seen in the picture above).

I didn't know if this is standard across all/most monospaced fonts. If it is, then I guess I can fix it so that full-width chars count as ~1.9 chars wide and then the paragraph will be visually the right width (vscode does it this way already, but it's not a "hard" wrap).

I also need to do work on performance before releasing the final version.

**Comment by ProgramFan** [comment]
Thanks @stkb for your hard work. I have tested it with my markdown documents and it works like a charm.

My opinion on the char width: Chinese characters are usually treated as double-width ones. And we do wrapping mainly to make it look better with most fonts. So I would recommend sticking to the 2-column rule for Chinese chars.

**Comment by stkb** [comment]
@ProgramFan thanks!
 
I can always change the exact relative-width of East Asian characters later if necessary, or even make it configurable. 

I also need to fix the autowrap feature so that it works with CJK text

**Comment by starship863** [comment]
Thanks @stkb very much for this exciting improvement!

The treatment of Chinese character as double-width is exactly the standard way. 
The same treatment is adopted since the first Chinese character displayed on a computer screen.

I have tested the new 1.9.0 beta1 version, it works like a charm on my Chinese documents.

Believe it or not, it is your extension that finally complete the VSCode to be the best editor for CJK documents.

**Comment by stkb** [comment]
@starship863 Thanks for the comments; it's very high praise indeed :)

I've now published v1.9.0 which is the same as the beta, with also correcting the autowrap column.

However I'm still not fully happy with the autowrap. Normally with for example English, you have to press space or enter for it to trigger. Since you don't really use spaces in Chinese, I did try to get it to just wrap automatically after typing Chinese characters.

However that didn't work out because I ran into problems with how IME's insert text into VSCode. So for now, you still have to press space, enter or tab to trigger the autowrap (when the IME window is closed).

I'm still going to keep working on a solution to make this better.

I will close this issue now since I think the main issue is supported. You can of course let me know here or on another issue if there are problems.
