### ISSUE TITLE
rewrap causes entire file to be re-syntax-highlighted

### ISSUE THREAD

**Issue by joelhock** [stkb/Rewrap#78]
Noticeable on large files especially, but rewrapping comments causes the entire text of the file to go plain white while it is re-syntax-highlighted.  I've noticed the effect on both c++ and javascript files.  A small amount of debugging shows edit.startLine always being 0 and edit.endLine always being the last line in the file.

It's just a small annoyance in an outstanding extension--thanks for all your work!

**Comment by stkb** [comment]
Actually I've noticed this myself lately. A couple of versions back I simplified some code but it meant the edit replaced the whole file. It's been on my task list since to do some proper profiling/performance work and see the impact (for all I knew vscode might do a diff on the edit anyway -- like VS does). But other issues have kept me busy :)

I still need to do the performance work but there's a quick fix I can apply here which should help.

**Comment by stkb** [comment]
I've just uploaded a beta version that has a fix (I think it's a noticeable difference). If you'd like to try it you can download it from https://github.com/stkb/Rewrap/releases/tag/v1.8.0-beta2.

**Comment by joelhock** [comment]
works great--thank you!!

**Comment by stkb** [comment]
Fixed in v1.8.0
