### ISSUE TITLE
Turn on toggle auto-wrap for certain file type

### ISSUE THREAD

**Issue by fwang2** [stkb/Rewrap#81]
I usually turn on auto-wrap whenever I work on Latex files.
Is there a way to toggle it on automatically? 

Thanks

**Comment by stkb** [comment]
Hi, I've had this feature in mind; but first, does just leaving it on permanently not work for you? It only affects comments in source code files anyway.

**Comment by fwang2** [comment]
Maybe I am missing something: the preferred setting for the auto-wrap is, if it is programming file type (python, C/C++ etc.), turn it off by default; for text, tex, markdown, turn it on by default. Right now, it is not clear to me what the default setting is: once I turn it on for a certain workspace, it will stay on, right?

**Comment by stkb** [comment]
No that's not quite right:

If you're installed the extension for the first time, auto-wrap will be off (for all files).

If you turn it on, it will be on for **all** files, including python, C/C++. Naturally, in those sorts of files, you don't want it activating on code lines, so there it only activates within comment lines anyway.

Now this is correct: once you turn it on, it stays on (+between sessions) until you turn it off again. This wasn't the case when I first added the feature (you had keep enabling it after opening vscode), but was fixed in the next version.

I use vscode with it enabled all the time. I don't know if you already saw [the wiki page](https://github.com/stkb/Rewrap/wiki/Auto-wrap) on the feature; it may be that I need to clarify some things there.

(If you have multiple vscode windows open it's a bit more complicated: turning it on in one window doesn't affect the other window (but new windows opened will get the 'new' setting). There may be something I need to fix there.)

**Comment by fwang2** [comment]
okay, I think I got it (as far as its "on" behavior goes): once it is turned on, even without per file type setting, it behaves differently for **code file**: only affects the comment line, which is a pretty sensible setting. If that is the case, I think it will do without the per file type setting. 

Thanks for the clarification.
